server:
  port: 8000

zuul:
  routes:
    persona:
      path: /personas/**
      serviceId: persona-testing
    archivo:
      path:  /archivo/**
      serviceId: archivo-testing

spring:
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
