server:
  port: 8000

zuul:
  sensitiveHeaders: Cookie,Set-Cookie,Authorization
  routes:
    persona:
      path: /personas/**
      serviceId: persona-testing
    archivo:
      path: /archivos/**
      serviceId: archivo-testing

spring:
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
logging:
   level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
            
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
                
feign:
  hystrix:
  enabled: true
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
